server {
    listen 80;
    server_name _;

    # Vue 3 SPA 路由（history 模式）
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

}
